# Generated by Django 4.0.6 on 2022-07-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('dn', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Driver numer')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Driver name')),
                ('contact', models.CharField(max_length=20)),
                ('source', models.TextField()),
                ('destination', models.TextField()),
            ],
            options={
                'verbose_name': 'Driver',
            },
        ),
        migrations.CreateModel(
            name='Userprof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='User name')),
                ('contact', models.CharField(max_length=20)),
                ('source', models.TextField()),
                ('destination', models.TextField()),
            ],
            options={
                'verbose_name': 'Userprof',
            },
        ),
    ]
