# Generated by Django 4.0.6 on 2022-07-12 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprof',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='userprof',
            name='source',
        ),
        migrations.AddField(
            model_name='userprof',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
