# Generated by Django 4.0.6 on 2022-07-12 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userprof_destination_remove_userprof_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprof',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
