# Generated by Django 4.0.6 on 2022-07-12 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_driver_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='my date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
