# Generated by Django 4.0.6 on 2022-07-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_driver_date_driver_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='date',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='time',
        ),
    ]
